# Generated by Django 3.1.1 on 2020-09-16 05:49

from django.db import migrations, models
import sunyong.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('vid', models.FileField(blank=True, null=True, upload_to=sunyong.models.user_upload_to)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
